"""Emit the Android vector drawables used by the splash screen.

Two assets are produced:

  splash_icon.xml   the mark, sized for the Android 12+ system splash slot
  splash_mark.xml   the mark plus the app name, used as the launch background so
                    pre-Android-12 launches show the same composed screen rather
                    than a bare mark

The X is drawn as four stroked segments that stop short of the crossing, so the
reticle reads without needing a clip path. VectorDrawable clip paths cannot
express a hole, and the system masks the splash icon to a circle, so the mark is
scaled to 80% to stay well inside that mask.

Prints the splash icon on stdout; regenerate both with:
    python3 scripts/gen_splash_vector.py > android/app/src/main/res/drawable/splash_icon.xml
    python3 scripts/gen_splash_vector.py --mark > android/app/src/main/res/drawable/splash_mark.xml
"""

import math
import sys

VIEW = 108.0
STROKE = 9.0

MARK_W, MARK_H = 56.0, 44.0
F_W = 24.0
X_X, X_W = 28.0, 28.0
X_CX, X_CY = X_X + X_W / 2, MARK_H / 2
GAP = 5.5  # along the diagonal; reads as a small reticle opening

SCALE = 0.8  # keeps the mark inside the circular mask the system applies


def mark_paths(ox, oy, scale):
    """The mark's drawable paths, placed at (ox, oy) and scaled.

    Split out so both the bare splash icon and the composed background can reuse
    exactly the same geometry as the in-app BrandMark.
    """
    def t(x, y):
        return round(ox + x * scale, 2), round(oy + y * scale, 2)

    paths = []

    # F: stem, top arm, middle arm.
    rects = [
        (0.0, 0.0, STROKE, MARK_H),
        (0.0, 0.0, F_W, STROKE),
        (0.0, MARK_H / 2 - STROKE / 2, F_W - 9, STROKE),
    ]
    for x, y, w, h in rects:
        x1, y1 = t(x, y)
        x2, y2 = t(x + w, y + h)
        paths.append(
            f'    <path android:fillColor="#FFFFFFFF" '
            f'android:pathData="M{x1},{y1} L{x2},{y1} L{x2},{y2} L{x1},{y2} Z"/>'
        )

    # X: four stroked segments.
    theta = math.atan2(MARK_H, X_W)
    ct, st = math.cos(theta), math.sin(theta)
    gx, gy = GAP * ct, GAP * st
    segs = [
        (X_X, 0.0, X_CX - gx, X_CY - gy),
        (X_CX + gx, X_CY + gy, X_X + X_W, MARK_H),
        (X_X + X_W, 0.0, X_CX + gx, X_CY - gy),
        (X_CX - gx, X_CY + gy, X_X, MARK_H),
    ]
    for x1, y1, x2, y2 in segs:
        sx1, sy1 = t(x1, y1)
        sx2, sy2 = t(x2, y2)
        paths.append(
            f'    <path android:strokeColor="#FFFFFFFF" '
            f'android:strokeWidth="{round(STROKE * scale, 2)}" '
            f'android:pathData="M{sx1},{sy1} L{sx2},{sy2}"/>'
        )

    return paths


def splash_icon():
    ox = (VIEW - MARK_W * SCALE) / 2
    oy = (VIEW - MARK_H * SCALE) / 2
    body = mark_paths(ox, oy, SCALE)
    return [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/gen_splash_vector.py; do not edit by hand. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{VIEW}dp"',
        f'    android:height="{VIEW}dp"',
        f'    android:viewportWidth="{VIEW}"',
        f'    android:viewportHeight="{VIEW}">',
        *body,
        '</vector>',
    ]


def splash_mark():
    """Mark plus a baseline rule, on the 108dp splash canvas.

    Rendered as vectors rather than a bitmap so it stays crisp at every density
    without shipping one raster per bucket. A short low-opacity rule under the
    mark reads as a deliberate composition; faking lettering with stroked paths
    would not.

    The mark is nudged above centre to leave room for the rule, which is what
    makes the composed screen look intentional rather than top-heavy.
    """
    ox = (VIEW - MARK_W * SCALE) / 2
    oy = 16.0
    body = mark_paths(ox, oy, SCALE)

    rule_y = oy + MARK_H * SCALE + 18.0
    body.append(
        f'    <path android:fillColor="#40FFFFFF" '
        f'android:pathData="M34,{rule_y} L74,{rule_y} L74,{rule_y + 1.5} L34,{rule_y + 1.5} Z"/>'
    )

    return [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/gen_splash_vector.py (mark mode); do not edit by hand. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{VIEW}dp"',
        f'    android:height="{VIEW}dp"',
        f'    android:viewportWidth="{VIEW}"',
        f'    android:viewportHeight="{VIEW}">',
        *body,
        '</vector>',
    ]


def main():
    mark_mode = "--mark" in sys.argv
    lines = splash_mark() if mark_mode else splash_icon()
    print("\n".join(lines))


if __name__ == "__main__":
    main()
