"""Emit the Android vector drawable used as the splash-screen icon.

The X is drawn as four stroked segments that stop short of the crossing, so
the reticle reads without needing a clip path. VectorDrawable clip paths
cannot express a hole, and the system masks this icon to a circle, so the
mark is scaled to 80% to stay well inside that mask.

Prints the XML on stdout; regenerate with:
    python3 scripts/gen_splash_vector.py > android/app/src/main/res/drawable/splash_icon.xml
"""

import math

VIEW = 108.0
STROKE = 9.0

MARK_W, MARK_H = 56.0, 44.0
F_W = 24.0
X_X, X_W = 28.0, 28.0
X_CX, X_CY = X_X + X_W / 2, MARK_H / 2
GAP = 5.5  # along the diagonal; reads as a small reticle opening

SCALE = 0.8  # keeps the mark inside the circular mask the system applies


def main():
    # Centre the mark in the viewport at the chosen scale.
    ox = (VIEW - MARK_W * SCALE) / 2
    oy = (VIEW - MARK_H * SCALE) / 2

    def t(x, y):
        return round(ox + x * SCALE, 2), round(oy + y * SCALE, 2)

    theta = math.atan2(MARK_H, X_W)
    ct, st = math.cos(theta), math.sin(theta)
    gx, gy = GAP * ct, GAP * st

    segs = [
        (X_X, 0.0, X_CX - gx, X_CY - gy),
        (X_CX + gx, X_CY + gy, X_X + X_W, MARK_H),
        (X_X + X_W, 0.0, X_CX + gx, X_CY - gy),
        (X_CX - gx, X_CY + gy, X_X, MARK_H),
    ]

    out = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/gen_splash_vector.py; do not edit by hand. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{VIEW}dp"',
        f'    android:height="{VIEW}dp"',
        f'    android:viewportWidth="{VIEW}"',
        f'    android:viewportHeight="{VIEW}">',
    ]

    # F: stem, top arm, middle arm.
    rects = [
        (0.0, 0.0, STROKE, MARK_H),
        (0.0, 0.0, F_W, STROKE),
        (0.0, MARK_H / 2 - STROKE / 2, F_W - 9, STROKE),
    ]
    for x, y, w, h in rects:
        x1, y1 = t(x, y)
        x2, y2 = t(x + w, y + h)
        out.append(
            f'    <path android:fillColor="#FFFFFFFF" '
            f'android:pathData="M{x1},{y1} L{x2},{y1} L{x2},{y2} L{x1},{y2} Z"/>'
        )

    # X: four stroked segments.
    for x1, y1, x2, y2 in segs:
        sx1, sy1 = t(x1, y1)
        sx2, sy2 = t(x2, y2)
        out.append(
            f'    <path android:strokeColor="#FFFFFFFF" '
            f'android:strokeWidth="{round(STROKE * SCALE, 2)}" '
            f'android:pathData="M{sx1},{sy1} L{sx2},{sy2}"/>'
        )

    out.append("</vector>")
    print("\n".join(out))


if __name__ == "__main__":
    main()
